/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HeadscaleServiceMoveNodeBody
 */
export interface HeadscaleServiceMoveNodeBody {
    /**
     * 
     * @type {string}
     * @memberof HeadscaleServiceMoveNodeBody
     */
    user?: string;
}

/**
 * Check if a given object implements the HeadscaleServiceMoveNodeBody interface.
 */
export function instanceOfHeadscaleServiceMoveNodeBody(value: object): value is HeadscaleServiceMoveNodeBody {
    return true;
}

export function HeadscaleServiceMoveNodeBodyFromJSON(json: any): HeadscaleServiceMoveNodeBody {
    return HeadscaleServiceMoveNodeBodyFromJSONTyped(json, false);
}

export function HeadscaleServiceMoveNodeBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeadscaleServiceMoveNodeBody {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function HeadscaleServiceMoveNodeBodyToJSON(json: any): HeadscaleServiceMoveNodeBody {
    return HeadscaleServiceMoveNodeBodyToJSONTyped(json, false);
}

export function HeadscaleServiceMoveNodeBodyToJSONTyped(value?: HeadscaleServiceMoveNodeBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
    };
}

