/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Route } from './V1Route';
import {
    V1RouteFromJSON,
    V1RouteFromJSONTyped,
    V1RouteToJSON,
    V1RouteToJSONTyped,
} from './V1Route';

/**
 * 
 * @export
 * @interface V1GetRoutesResponse
 */
export interface V1GetRoutesResponse {
    /**
     * 
     * @type {Array<V1Route>}
     * @memberof V1GetRoutesResponse
     */
    routes?: Array<V1Route>;
}

/**
 * Check if a given object implements the V1GetRoutesResponse interface.
 */
export function instanceOfV1GetRoutesResponse(value: object): value is V1GetRoutesResponse {
    return true;
}

export function V1GetRoutesResponseFromJSON(json: any): V1GetRoutesResponse {
    return V1GetRoutesResponseFromJSONTyped(json, false);
}

export function V1GetRoutesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetRoutesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'routes': json['routes'] == null ? undefined : ((json['routes'] as Array<any>).map(V1RouteFromJSON)),
    };
}

export function V1GetRoutesResponseToJSON(json: any): V1GetRoutesResponse {
    return V1GetRoutesResponseToJSONTyped(json, false);
}

export function V1GetRoutesResponseToJSONTyped(value?: V1GetRoutesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'routes': value['routes'] == null ? undefined : ((value['routes'] as Array<any>).map(V1RouteToJSON)),
    };
}

